### ISSUE TITLE
ShamirInterfaces

### ISSUE THREAD

**Issue by jorabin** [derecalliance/cryptography#11]
given the refactoring of storeshare.proto I think `ShamirInterfaces` spec is wrong . It should just  provide for splitting a byte[] and recombining byte[]s the other parameters are not relevant?

Pls confirm @rsinha that this is actually what it implements at present?

this is actually what is needed, I think:

```java
/**
 * Interface for sharing and recombining shares as byte arrays.
 */
public interface DeRecShareProvider {
    /**
     * Create shares from an array
     * @param bytesToShare the bytes to share
     * @param count the number of shares
     * @param threshold the recombination threshold
     * @return a list of count shares
     */
    List<byte[]> share (byte[] bytesToShare, int count, int threshold);

    /**
     * Recombine some shares  
     * @param shares the shares to combine
     * @return the combined shares
     */
    byte [] combine (List<byte[]> shares);
}
```

**Comment by jorabin** [comment]
OK< we need to add the secretId and the version number for committed DeRecShare purposes

**Comment by rsinha** [comment]
Can we close this issue (and create a new one if appropriate)?
`jni/src/DerecCryptoInterface.java` implements the discussed interface.
