### ISSUE TITLE
Examples of Signature Key Pairs in PEM format. 

### ISSUE THREAD

**Issue by ehanoc** [derecalliance/cryptography#18]
# What

As mentioned in https://github.com/derecalliance/protobufs/issues/5,  `DeRecCryptoInterface#signatureKeyGen` the generated keys need to be in PEM format, compliant with [RFC-7468](https://datatracker.ietf.org/doc/html/rfc7468).  

We need examples to work as documentation and potentially as test vectors

**Comment by ehanoc** [comment]
@rsinha @lbaird @johnalanwoods Since we have moved from RSA to ECC, i'm assuming the `DeRecCryptoInterface#encryptionKeyGen` is unnecessary to document since we would be generating encryption keys based on ECIES, ECDH. 

Looks like something we can remove from the interface?

**Comment by rsinha** [comment]
While it just serves to wrap the underlying ECIES KeyGen, we may want to preserve this function to avoid having the developer to find that implementation, and choose amongst the various crates that implement ECIES. WDYT?

**Comment by ehanoc** [comment]
Then we could update the interface since ECIES / ECDH requires the other party's public key in other to generate the symmetric secret. If we have multiple helpers / parties we need to specify which are creating the symmetric secret for as for each party that would be different symmetric secrets created.
