### ISSUE TITLE
Encrypt, Decrypt, Sign, and Verify functionality not supported

### ISSUE THREAD

**Issue by diptimahamuni** [derecalliance/cryptography#25]
For pairing messages, we need the functionality to encrypt, decrypt, sign, and verify separately. Without implementation of these functions, a library would not be able to support pairing.

For the Pair Request message, the receiver needs to decrypt (but not verify initially) then parse the message, and then verify using the signature in the decrypted message. The cryptography library should provide separate `decrypt()` and `verify()` functions. Additionally, `sign()` and `encrypt()` functions would be needed as well.

**Comment by rsinha** [comment]
Closed by https://github.com/derecalliance/cryptography/pull/27
